name: Deploy to Infomaniak

on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Deploy dist dir
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: aw256.ftp.infomaniak.com #  Remplacez par l'adresse de votre serveur FTP
          username: ${{ secrets.FTP_USERNAME }} # Utilisez les secrets GitHub pour stocker en toute sécurité votre nom d'utilisateur FTP
          password: ${{ secrets.FTP_PASSWORD }} # Utilisez les secrets GitHub pour stocker en toute sécurité votre mot de passe FTP
          server-dir: / # Remplacez par le répertoire où vous souhaitez déployer votre site web
          local-dir: ./dist/ # Déployez uniquement le dossier temporaire contenant le contenu de dist
          dangerous-clean-slate: true
      - name: Deploy assets dir
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: aw256.ftp.infomaniak.com # Remplacez par l'adresse de votre serveur FTP
          username: ${{ secrets.FTP_USERNAME }} # Utilisez les secrets GitHub pour stocker en toute sécurité votre nom d'utilisateur FTP
          password: ${{ secrets.FTP_PASSWORD }} # Utilisez les secrets GitHub pour stocker en toute sécurité votre mot de passe FTP
          server-dir: /img/ # Remplacez par le répertoire où vous souhaitez déployer votre site web
          local-dir: ./img/ # Déployez uniquement le dossier temporaire contenant le contenu de dist
          dangerous-clean-slate: true
      - name: replace data
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: aw256.ftp.infomaniak.com # Remplacez par l'adresse de votre serveur FTP
          username: ${{ secrets.FTP_USERNAME }} # Utilisez les secrets GitHub pour stocker en toute sécurité votre nom d'utilisateur FTP
          password: ${{ secrets.FTP_PASSWORD }} # Utilisez les secrets GitHub pour stocker en toute sécurité votre mot de passe FTP
          server-dir: /data/ # Remplacez par le répertoire où vous souhaitez déployer votre site web
          local-dir: ./data/ # Déployez uniquement le dossier temporaire contenant le contenu de dist
          dangerous-clean-slate: true
              - name: replace favicon
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: aw256.ftp.infomaniak.com # Remplacez par l'adresse de votre serveur FTP
          username: ${{ secrets.FTP_USERNAME }} # Utilisez les secrets GitHub pour stocker en toute sécurité votre nom d'utilisateur FTP
          password: ${{ secrets.FTP_PASSWORD }} # Utilisez les secrets GitHub pour stocker en toute sécurité votre mot de passe FTP
          server-dir: /favicon.ico # Remplacez par le répertoire où vous souhaitez déployer votre site web
          local-dir: ./favicon.ico # Déployez uniquement le dossier temporaire contenant le contenu de dist
          dangerous-clean-slate: true
